# Generated by Django 3.2 on 2022-12-29 08:29

from django.db import migrations, models
import reviews.validator


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(validators=[reviews.validator.validate_year], verbose_name='Год произведения'),
        ),
    ]
