# Generated by Django 3.2 on 2022-12-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True, default='-пусто-', null=True, verbose_name='Описание произведения'),
        ),
    ]
